name: Build Mitsuba 3 on Ubuntu
inputs:
  github_token:
    required: true
    description: "GitHub token defined by the workflow"
runs:
  using: composite
  steps:
  - name: Install Mitsuba build dependencies
    shell: bash
    run: |
      sudo apt update
      sudo apt install -y cmake ccache ninja-build libpng-dev libjpeg-dev 
      python -m pip install setuptools typing_extensions numpy

  - name: Restore ccache
    id: cache-mitsuba
    uses: actions/cache/restore@v4
    with:
      path: |
        ~/.cache
      key: build-ubuntu-${{ github.run_id }}
      restore-keys: |
        build-ubuntu-

  - name: Checkout Mitsuba 3 repo
    uses: actions/checkout@v4
    with:
      repository: mitsuba-renderer/mitsuba3
      path: mitsuba3
      submodules: recursive
      fetch-depth: 0

  - name: Restore timestamps 
    uses: chetan/git-restore-mtime-action@v2
    with:
      working-directory: mitsuba3


  - name: Build Mitsuba 3
    shell: bash
    run: |
      cd mitsuba3
      mkdir -p build
      export CMAKE_CXX_COMPILER_LAUNCHER=ccache
      export CCACHE_DEBUGDIR=$GITHUB_WORKSPACE/ccache-debug
      cd build
      cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release 
      ninja

  - name: Store ccache
    if: always()
    uses: actions/cache/save@v4
    with:
      key: build-ubuntu-${{ github.run_id }}
      path: |
        ~/.cache

