# Runs on every pushed version tag. It runs the test suite, builds the
# extension zips, and creates a new draft entry in the release section.
name: Release

on:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  release:
    name: "Publish draft release"
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Download the extension zips
      uses: actions/download-artifact@v4
      with:
        name: extension-zips
        path: dist

    - name: Create GitHub draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.zip"
        artifactErrorsFailBuild: true
        bodyFile: "release/release_body_template.md"
        draft: true
        name: "Mitsuba-Blender ${{ github.ref_name }}"
